
insert into ProductTypes(TypeName) values ('KNITTING ')
insert into ProductTypes(TypeName) values ('WOVEN')


insert into ProductStyles(StyleName) values ('PRINT')
insert into ProductStyles(StyleName) values ('PLAIN DYED')


insert into Seasons(SeasonName) values ('SUMMER')
insert into Seasons(SeasonName) values ('AUTUMN')
insert into Seasons(SeasonName) values ('WINTER')
insert into Seasons(SeasonName) values ('SPRING')

insert into DesignTypes(DesignName) values ('ABSTRACT')
insert into DesignTypes(DesignName) values ('DORTS')
insert into DesignTypes(DesignName) values ('STRIPE')
insert into DesignTypes(DesignName) values ('CHECKS')
insert into DesignTypes(DesignName) values ('SMALL FLOWER')
insert into DesignTypes(DesignName) values ('BIG FLOWER')
insert into DesignTypes(DesignName) values ('GEOMETRICAL')
insert into DesignTypes(DesignName) values ('CLASSIC')
insert into DesignTypes(DesignName) values ('PEZLI')
insert into DesignTypes(DesignName) values ('CLOUDY')
insert into DesignTypes(DesignName) values ('BLACK & WHITE')
insert into DesignTypes(DesignName) values ('PANNEL')
insert into DesignTypes(DesignName) values ('BORDER')
insert into DesignTypes(DesignName) values ('OMBREY')


insert into Colors(ColorName) values ('BLACK')
insert into Colors(ColorName) values ('WHITE')
insert into Colors(ColorName) values ('MILK')
insert into Colors(ColorName) values ('NAVY ')
insert into Colors(ColorName) values ('SKY')
insert into Colors(ColorName) values ('INDIGO')
insert into Colors(ColorName) values ('ROYAL BLUE')
insert into Colors(ColorName) values ('TRKOISH BLUE')
insert into Colors(ColorName) values ('RED')
insert into Colors(ColorName) values ('PINK')
insert into Colors(ColorName) values ('PEACH')
insert into Colors(ColorName) values ('MARRON')
insert into Colors(ColorName) values ('WINE')
insert into Colors(ColorName) values ('PURPLE')
insert into Colors(ColorName) values ('GREY')
insert into Colors(ColorName) values ('YELLOW')
insert into Colors(ColorName) values ('LEMON')
insert into Colors(ColorName) values ('ORANGE')
insert into Colors(ColorName) values ('MUSTERED')
insert into Colors(ColorName) values ('BEIGE')
insert into Colors(ColorName) values ('BROWN')
insert into Colors(ColorName) values ('CHOCOLATE')
insert into Colors(ColorName) values ('COFFEE')
insert into Colors(ColorName) values ('GREEN')
insert into Colors(ColorName) values ('OLIVE')
insert into Colors(ColorName) values ('PARROT')
insert into Colors(ColorName) values ('SEA GREEN')

insert into OverWorkTypes(OverWorkName) values ('EMBROIDERY')
insert into OverWorkTypes(OverWorkName) values ('BALPO')
insert into OverWorkTypes(OverWorkName) values ('METAIL')
insert into OverWorkTypes(OverWorkName) values ('FOIL')
insert into OverWorkTypes(OverWorkName) values ('JACQUARD')
insert into OverWorkTypes(OverWorkName) values ('RACTIVE')
insert into OverWorkTypes(OverWorkName) values ('DOUBLE PRINT')
insert into OverWorkTypes(OverWorkName) values ('SPANGLE')
insert into OverWorkTypes(OverWorkName) values ('FUKRO')
insert into OverWorkTypes(OverWorkName) values ('EMBOSS')
insert into OverWorkTypes(OverWorkName) values ('FLOCK')
insert into OverWorkTypes(OverWorkName) values ('CRUSH')
insert into OverWorkTypes(OverWorkName) values ('BRUSH')
insert into OverWorkTypes(OverWorkName) values ('LAMINATION')
insert into OverWorkTypes(OverWorkName) values ('DOBBY')
insert into OverWorkTypes(OverWorkName) values ('BURN OUT')
